### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by baibhavKumar1** [Web3VitePress/Web3VitePress#3]
Github link on the website is not working .
Navbar on home page is not being rendered properly.
![image](https://user-images.githubusercontent.com/109906215/210817034-d77f2e70-fedd-457d-a636-c8621f87f7d3.png)

**Comment by Web3HackerWorld** [comment]
what is your device?

**Comment by baibhavKumar1** [comment]
I am using chrome browser, The navbar transparency is working on other pages than landing page.

**Comment by Web3HackerWorld** [comment]
> I am using chrome browser, The navbar transparency is working on other pages than landing page.

Can you try this page to see if it works? https://vitepress.vuejs.org/

**Comment by baibhavKumar1** [comment]
Yes, it is working properly.

**Comment by Web3HackerWorld** [comment]
> Yes, it is working properly.

ok, maybe because I bring in the tailwindcss cause the bug, will try fix it later! I am making a big plan for this open-source project ;)

**Comment by baibhavKumar1** [comment]
Great! I will try to fix it once I'm free.
